package test;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;

public class admin_window_design {
    private JPanel mainWindow;
    private JPanel toppanel;
    private JPanel leftpanel;
    private JPanel rightpanel;
    private JButton button1;
    private JButton button2;

    public static void main(String[] args) {
        JFrame frame = new JFrame("admin_window_design");
        frame.setContentPane(new admin_window_design().mainWindow);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainWindow = new JPanel();
        mainWindow.setLayout(new BorderLayout(0, 0));
        mainWindow.setPreferredSize(new Dimension(900, 675));
        toppanel = new JPanel();
        toppanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        toppanel.setPreferredSize(new Dimension(900, 75));
        mainWindow.add(toppanel, BorderLayout.NORTH);
        leftpanel = new JPanel();
        leftpanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,center:30px:noGrow,center:d:noGrow"));
        leftpanel.setPreferredSize(new Dimension(200, 600));
        mainWindow.add(leftpanel, BorderLayout.WEST);
        button1 = new JButton();
        button1.setPreferredSize(new Dimension(150, 40));
        button1.setText("Button");
        CellConstraints cc = new CellConstraints();
        leftpanel.add(button1, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        button2 = new JButton();
        button2.setPreferredSize(new Dimension(150, 40));
        button2.setText("Button");
        leftpanel.add(button2, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        rightpanel = new JPanel();
        rightpanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        rightpanel.setPreferredSize(new Dimension(700, 600));
        mainWindow.add(rightpanel, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainWindow;
    }

}
