package test;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class book_chart_design {
    private JPanel p;
    private JPanel book;
    private JPanel rankInfo;
    private JButton button1;

    public static void main(String[] args) {
        JFrame frame = new JFrame("book_chart_design");
        frame.setContentPane(new book_chart_design().p);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        p = new JPanel();
        p.setLayout(new FormLayout("center:d:noGrow,center:d:noGrow", "center:d:noGrow"));
        p.setPreferredSize(new Dimension(200, 200));
        rankInfo = new JPanel();
        rankInfo.setLayout(new FormLayout("center:d:noGrow", "center:d:noGrow,center:10px:noGrow,center:d:noGrow,center:d:noGrow"));
        rankInfo.setPreferredSize(new Dimension(50, 200));
        CellConstraints cc = new CellConstraints();
        p.add(rankInfo, cc.xy(1, 1));
        rankInfo.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setPreferredSize(new Dimension(40, 40));
        label1.setText("Label");
        rankInfo.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        label2.setPreferredSize(new Dimension(40, 40));
        label2.setText("Label");
        rankInfo.add(label2, cc.xy(1, 3));
        final JLabel label3 = new JLabel();
        label3.setPreferredSize(new Dimension(40, 25));
        label3.setText("Label");
        rankInfo.add(label3, cc.xy(1, 4));
        book = new JPanel();
        book.setLayout(new FormLayout("fill:d:noGrow", "center:d:noGrow"));
        book.setPreferredSize(new Dimension(150, 200));
        p.add(book, cc.xy(2, 1));
        button1 = new JButton();
        button1.setPreferredSize(new Dimension(150, 200));
        button1.setText("Button");
        book.add(button1, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return p;
    }
}
